name: ci

on:
#  push:
#    branches:
#      - 'main'
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            "albiondata/albiondata-server-rails:${{ github.event.pull_request && github.head_ref || github.ref_name }}"
            "albiondata/albiondata-server-rails:latest"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
